# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: maxon
  joint_model_group_pose: start
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_link1_joint
    - link1_link2_joint
  sim_control_mode: 0  # 0: position, 1: velocity
controller_list:
  - name: /maxon/canopen_motor/joint_trajectory_controller
    type: FollowJointTrajectory
    joints: 
      - base_link1_joint
      - link1_link2_joint
    action_ns: follow_joint_trajectory
